In [17]:
import torch

In [18]:
x = torch.ones(2,3,requires_grad =True)

In [19]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [20]:
y = x + 2
print(y)
print(x)

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)
tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [21]:
z = y * y * 3
out = z.mean()

print(z)
print(out)

tensor([[27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward1>)


In [22]:
a = torch.randn(2,2)
a = ((a +3) / (a - 1))
print(a.requires_grad)

False


In [23]:
a.requires_grad_(True)
print(a.requires_grad)

b = (a*a).sum()
print(b.grad_fn)

True


In [24]:
out.backward()

In [25]:
print(x.grad)
print(x)

tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [27]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x * 2
print(y)
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-0.0701, -0.2620, -0.3713], requires_grad=True)
tensor([-0.1403, -0.5239, -0.7425], grad_fn=<MulBackward0>)
tensor([ -287.2744, -1073.0260, -1520.6776], grad_fn=<MulBackward0>)


In [28]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)


tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])


In [29]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
