In [1]:
from __future__ import print_function

In [2]:
import torch

In [10]:
#empty matrix
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00,  1.0842e-19, -2.0634e+18],
        [-3.6902e+19,  5.6052e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-2.0656e+18, -1.5849e+29, -2.0633e+18]])


In [11]:
#randomly intialized
x = torch.rand(5,3)
print(x)

tensor([[0.7142, 0.3083, 0.4392],
        [0.3544, 0.8315, 0.2872],
        [0.5943, 0.9801, 0.4405],
        [0.3866, 0.3658, 0.6457],
        [0.5860, 0.5728, 0.7406]])


In [9]:
#matrix filled with zeros
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [14]:
x=torch.tensor([3.5,7])
print(x)

tensor([3.5000, 7.0000])


In [16]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [18]:
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[ 1.1722,  1.1708, -0.2452],
        [ 0.8840, -0.2739, -0.0879],
        [-0.4428,  0.5010, -0.6817],
        [-1.0586, -0.8429, -0.9383],
        [ 0.1207, -1.8914, -0.5150]])


In [19]:
print(x.size())

torch.Size([5, 3])


In [21]:
y=torch.rand(5,3)
print(y)

tensor([[0.3190, 0.9224, 0.7151],
        [0.2411, 0.1670, 0.9480],
        [0.7487, 0.3228, 0.6603],
        [0.3793, 0.1475, 0.9633],
        [0.9294, 0.2475, 0.9746]])


In [23]:
print(x+y) #add

tensor([[ 1.4912,  2.0932,  0.4699],
        [ 1.1251, -0.1069,  0.8601],
        [ 0.3059,  0.8238, -0.0214],
        [-0.6793, -0.6955,  0.0250],
        [ 1.0501, -1.6439,  0.4596]])


In [25]:
torch.add(x,y)

tensor([[ 1.4912,  2.0932,  0.4699],
        [ 1.1251, -0.1069,  0.8601],
        [ 0.3059,  0.8238, -0.0214],
        [-0.6793, -0.6955,  0.0250],
        [ 1.0501, -1.6439,  0.4596]])

In [28]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[ 1.4912,  2.0932,  0.4699],
        [ 1.1251, -0.1069,  0.8601],
        [ 0.3059,  0.8238, -0.0214],
        [-0.6793, -0.6955,  0.0250],
        [ 1.0501, -1.6439,  0.4596]])


In [29]:
y.add_(x)

tensor([[ 1.4912,  2.0932,  0.4699],
        [ 1.1251, -0.1069,  0.8601],
        [ 0.3059,  0.8238, -0.0214],
        [-0.6793, -0.6955,  0.0250],
        [ 1.0501, -1.6439,  0.4596]])

In [31]:
print(x[:,1])
print(x[1,2])

tensor([ 1.1708, -0.2739,  0.5010, -0.8429, -1.8914])
tensor(-0.0879)


In [34]:
result.size()

torch.Size([5, 3])

In [38]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[0.8986, 0.5244, 0.7019, 0.4026],
        [0.4297, 0.3920, 0.8281, 0.6199],
        [0.0717, 0.2272, 0.3580, 0.0043],
        [0.9347, 0.8249, 0.4294, 0.0755]])
tensor([0.8986, 0.5244, 0.7019, 0.4026, 0.4297, 0.3920, 0.8281, 0.6199, 0.0717,
        0.2272, 0.3580, 0.0043, 0.9347, 0.8249, 0.4294, 0.0755])
tensor([[0.8986, 0.5244, 0.7019, 0.4026, 0.4297, 0.3920, 0.8281, 0.6199],
        [0.0717, 0.2272, 0.3580, 0.0043, 0.9347, 0.8249, 0.4294, 0.0755]])


In [39]:
print(z)

tensor([[0.8986, 0.5244, 0.7019, 0.4026, 0.4297, 0.3920, 0.8281, 0.6199],
        [0.0717, 0.2272, 0.3580, 0.0043, 0.9347, 0.8249, 0.4294, 0.0755]])


In [41]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [42]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [43]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [44]:
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [46]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [47]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(x.to("cpu",torch.double))